name: Feedback form
on: 
   push:
     branchees:
      main

jobs:
  builds:
     runs-on: ubuntu-latest
     steps:
         name: checkout code
uses: actions/checkout@v3

name: set up python
uses: action/set up python@v4
with: 
python-version: '3.10'

name: instll dependencies
run: pip install -r requirements.txt

name: run tests
run: pytest

